services:
  - type: web
    name: employee-management
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input
    startCommand: gunicorn workflowhub.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: employee-management
          property: host